# Generated by Django 5.1.15 on 2026-08-23 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sneakers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Custom Sneaker', max_length=150)),
                ('configuration', models.JSONField(help_text='Full 3D part configuration (colors, materials, finishes, custom text)')),
                ('preview_image_url', models.URLField(blank=True, max_length=1000)),
                ('total_price', models.DecimalField(decimal_places=2, default=11995.0, max_digits=10)),
                ('is_public', models.BooleanField(default=True, help_text='Showcase in community feed')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='sneakers.sneakermodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
